### ISSUE TITLE
Possible Issue when loading file data

### ISSUE THREAD

**Issue by jmscreation** [gorbit99/OLC-Font#1]
It is possible this could cause problems when loading a file that contains whitespace bytes (0x09 or 0x20)

Right shifting from a stream into an std::string reads up until a whitespace character is found. As this is supposed to be a binary file, I believe this to be problematic. 

https://github.com/gorbit99/OLC-Font/blob/b9e09016adf061a6a8fbf60367b96c4d8a955b9f/Build/olcPGEX_Fonts.h#L11

https://github.com/gorbit99/OLC-Font/blob/b9e09016adf061a6a8fbf60367b96c4d8a955b9f/Build/olcPGEX_Fonts.h#L12

**Comment by gorbit99** [comment]
The compression algorithm doesn't let that happen, we basically take the color as a 32 bit number, split it up into around 6 bit chunks and add 48 to the value, this means the result will be between 48 and 112 so from 0 to p, no whitespace characters in between.
